
# .streamlit/config.toml

[theme]
base="light"
primaryColor="#f0ff3d"

# The dark Shakers green for the main background.
backgroundColor="#033028"

# A slightly lighter dark green for elements like the sidebar and expanders.
secondaryBackgroundColor="#02211b"

# A light, readable text color that works on the dark background.
textColor="#FAFAFA"

# Use a standard sans-serif font.
font="sans serif"

[server]
# This helps if you're running on a network and want to avoid CORS issues.
enableCORS = false